# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-IntrospectionMethods
version:      1.002
version_from: 
installdirs:  site
requires:
    Tie::Array::CustomStorage:     0
    Tie::Hash::CustomStorage:      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
